### ISSUE TITLE
using yield in to_array breaks pyexcel/sheets/matrix.py

### ISSUE THREAD

**Issue by lausser** [pyexcel/pyexcel-io#14]
Hi,

import pyexcel
import pyexcel.ext.xlsx
import pyexcel.utils
workbook = pyexcel.get_book(file_name="sample.xlsx")

breaks, because in Matrix.__init__ -> uniform -> longest_row_number you call "len(array)"
But this array came out of  pyexcel-io's SheetReader.to_array which returns nowadays a generator, so...
TypeError: object of type 'generator' has no len()

IMHO there's no alternative to letting to_array() return a list again, otherwise any "i'm curious how long this thing is"-operations will empty out the generator.
One thing i just tried is:

def uniform(array):
    """Fill-in empty strings to empty cells to make it MxN

    :param list in_array: a list of arrays
    """ 
    # array has rows, a row has cells
    even_array = []
    for row in array:
        tmp_row = []
        for col in row:
            if col is None:
                tmp_row.append("")
            else:
                tmp_row.append(col)
            even_array.append(tmp_row)
    width = max(map(len, even_array))
    # now fill the short rows with empty cells
    for row in even_array:
        row_length = len(row)
        if row_length < width:
            row += [""] * (width - row_length)
    return width, even_array

But i don't know if this is efficient regarding Performance.

Gerhard

**Comment by chfw** [comment]
Hi Gerhard,

Thanks for your feedback. It is true that latest pyexcel-io v0.1.0 will break the matrix where pyexcel v< 0.2.0, because of to_array returns a generator, which won't have a length. So, I would recommend to take pyexcel=0.2.0 and all its pyexcel plugins to 0.1.0. 

I also take this chance to apologize to all pyexcel users for such a surprising api break. I have done a github rnd release but didn't attract much criticism. Hence, I pushed it out and looked forward to potential feedbacks.

The major move to use yield and generator is to tackle excel files that has huge data. At the moment, pyexcel 0.2.0 gives performance boost only to pyexcel.save_as and pyexcel.save_book_as. For other operations, there is no performance improvement yet. 

Yes, I agree with you that to return a list is the only way to know the length. Hence, pyexcel 0.2.0 [converts generator to an array](https://github.com/pyexcel/pyexcel/blob/master/pyexcel/sheets/matrix.py#L492) when get_sheet and get_book are called. That's why matrix in 0.2.0 won't break. 


Br,

Chenfu

**Comment by lausser** [comment]
Hi,
thanks, i'll update to 0.2.0 + 0.1.0. And thank you very much for these modules, they are so useful!
Gerhard
